### ISSUE TITLE
Question on SPI_SR_TCF

### ISSUE THREAD

**Issue by dlchambers** [xxxajk/spi4teensy3#11]
This question is to hopefully help me understand.
In send(), you set SPI_SR_TCF before SPI0_PUSHR
```
SPI0_SR = SPI_SR_TCF;
SPI0_PUSHR = SPI_PUSHR_CONT | b;
```
I would have expected that you'd do it in the reverse sequence, set the data then set the tx flag.
Any insight as to why flag-before-data would be appreciated.

-Dave

**Comment by xxxajk** [comment]
Sure....
From the reference manual, section 45.3.5 DSPI Status Register (SPIx_SR)
Field (bit) 31 is the Transfer Complete Flag
Indicates that all bits in a frame have been shifted out. 
**TCF remains set until it is cleared by writing a 1 to it.**

In other words, this ensures the flag is cleared, since it may be in an unknown state.
Then we push the data onto the FIFO.
Otherwise if the SPI module thinks the data is empty (which it could be) the flag won't be correct, and you would *think* that the data was sent when it is not sent yet. If there was data not sent yet, it does not matter, or if it was already empty, it does not matter, because right after we clear the bit, we send the data, and enforce that the select keeps the expected state on the /CS line..

Make sense?

**Comment by dlchambers** [comment]
Yes, thanks - makes sense. 
What confused me is that you clear TCF by writing a 1 to it. Usually "clear" means setting the bit to 0.

**Comment by xxxajk** [comment]
Ok :-) 
Well, on ARM, many peripherals you write a 1 to clear. This way you don't accidentally clear something you don't want to clear. It also allows you to do a write to a bitband address to get the same effects, and sometimes there are even separate set and clear bits. It really depends on the module and the register.

Let me know if you need anything else explained. You should also read 
Document Number: K20P64M72SF1RM "K20 Sub-Family Reference Manual"
This has all of the details for everything on the MCU.
This can be found here: [https://cache.freescale.com/files/32bit/doc/ref_manual/K20P64M72SF1RM.pdf](url)
